export const imgs = {
	"cat" : require("./cat.jpg"),
	"fox" : require("./fox.jpg"),
	"donkey" : require("./donkey.jpg"),
	"dolphin" : require("./dolphin.jpg"),
	"lion" : require("./lion.jpg"),
	"love" : require("./love.jpg"),
	"wait" : require("./wait.jpg"),
	"sleep" : require("./sleep.jpg"),
	"drink" : require("./drink.jpg"),
	"eat" : require("./eat.jpg"),
	"bed" : require("./bed.jpg"),
	"table" : require("./table.jpg"),
	"chair" : require("./chair.jpg"),
	"clock" : require("./clock.jpg"),
	"water" : require("./water.jpg"),
	"egypt" : require("./egypt.jpg"),
	"syria" : require("./syria.jpg"),
	"iraq" : require("./iraq.png"),
	"turkey" : require("./turkey.jpg"),
	"croatia" : require("./croatia.png"),
	}
